
def GetCPPPATH(BSP_ROOT, RTT_ROOT):
	CPPPATH=[
		BSP_ROOT + "/.",
		BSP_ROOT + "/applications",
		BSP_ROOT + "/applications/test",
		BSP_ROOT + "/applications/test/test_vector",
		BSP_ROOT + "/driver",
		BSP_ROOT + "/packages/lwext4-v2.0.0-dfsv2/include",
		BSP_ROOT + "/packages/lwext4-v2.0.0-dfsv2/ports/rtthread",
		BSP_ROOT + "/terminal",
		RTT_ROOT + "/components/dfs/dfs_v2/filesystems/devfs",
		RTT_ROOT + "/components/dfs/dfs_v2/filesystems/elmfat",
		RTT_ROOT + "/components/dfs/dfs_v2/filesystems/procfs",
		RTT_ROOT + "/components/dfs/dfs_v2/filesystems/ptyfs",
		RTT_ROOT + "/components/dfs/dfs_v2/filesystems/romfs",
		RTT_ROOT + "/components/dfs/dfs_v2/include",
		RTT_ROOT + "/components/drivers/include",
		RTT_ROOT + "/components/drivers/ktime",
		RTT_ROOT + "/components/drivers/ktime/inc",
		RTT_ROOT + "/components/drivers/phy",
		RTT_ROOT + "/components/drivers/smp_call",
		RTT_ROOT + "/components/drivers/virtio",
		RTT_ROOT + "/components/finsh",
		RTT_ROOT + "/components/libc/compilers/common/include",
		RTT_ROOT + "/components/libc/compilers/musl",
		RTT_ROOT + "/components/libc/posix/delay",
		RTT_ROOT + "/components/libc/posix/io/aio",
		RTT_ROOT + "/components/libc/posix/io/epoll",
		RTT_ROOT + "/components/libc/posix/io/eventfd",
		RTT_ROOT + "/components/libc/posix/io/poll",
		RTT_ROOT + "/components/libc/posix/io/signalfd",
		RTT_ROOT + "/components/libc/posix/io/stdio",
		RTT_ROOT + "/components/libc/posix/io/termios",
		RTT_ROOT + "/components/libc/posix/ipc",
		RTT_ROOT + "/components/libc/posix/libdl",
		RTT_ROOT + "/components/lwp",
		RTT_ROOT + "/components/lwp/arch/risc-v/rv64",
		RTT_ROOT + "/components/mm",
		RTT_ROOT + "/components/net/lwip/lwip-2.0.3/src/include",
		RTT_ROOT + "/components/net/lwip/lwip-2.0.3/src/include/ipv4",
		RTT_ROOT + "/components/net/lwip/lwip-2.0.3/src/include/netif",
		RTT_ROOT + "/components/net/lwip/port",
		RTT_ROOT + "/components/net/netdev/include",
		RTT_ROOT + "/components/net/sal/impl",
		RTT_ROOT + "/components/net/sal/include",
		RTT_ROOT + "/components/net/sal/include/dfs_net",
		RTT_ROOT + "/components/net/sal/include/socket",
		RTT_ROOT + "/components/net/sal/include/socket/sys_socket",
		RTT_ROOT + "/components/utilities/libadt/avl",
		RTT_ROOT + "/components/utilities/libadt/bitmap",
		RTT_ROOT + "/components/utilities/libadt/hashmap",
		RTT_ROOT + "/components/utilities/libadt/ref",
		RTT_ROOT + "/components/utilities/libadt/uthash",
		RTT_ROOT + "/components/utilities/resource",
		RTT_ROOT + "/components/utilities/utest",
		RTT_ROOT + "/include",
		RTT_ROOT + "/libcpu/risc-v/common64",
		RTT_ROOT + "/libcpu/risc-v/virt64",
	]

	return CPPPATH

def GetCPPDEFINES():
	CPPDEFINES=['RT_USING_MUSLLIBC', '__RTTHREAD__', 'CONFIG_HAVE_OWN_OFLAGS=0', 'RT_USING_LIBC', 'CONFIG_USE_DEFAULT_CFG']
	return CPPDEFINES

